import Header from '@/app/components/Header'
import './globals.css'
import { Alegreya, Della_Respira, Inter, Quicksand, Roboto } from 'next/font/google'

const inter = Quicksand({ weight: '500', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='w-screen overflow-x-hidden'>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
